apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-manage-your-civil-cases.fullname" . }}
  labels:
    {{- include "laa-manage-your-civil-cases.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "laa-manage-your-civil-cases.selectorLabels" . | nindent 4 }}
