name: Delete UAT release

on:
  pull_request_target:
    types:
      - closed

jobs:
  delete_uat_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Delete from UAT namespace
        id: delete_uat
        uses: ./.github/actions/delete-uat-release
      - name: Result
        shell: bash
        run: echo ${{ steps.delete_uat.outputs.delete-message }}\
